### ISSUE TITLE
rosdistro>=0.7.5' distribution was not found and is required by rosdep and performance_test: Cannot locate rosdep definition for [test_osrf_testing_tools_cpp]

### ISSUE THREAD

**Issue by spanthr** [ros2/performance_test#33]
rosdep install -y --from performance_test --ignore-src
Traceback (most recent call last):
File "/usr/local/bin/rosdep", line 6, in
from pkg_resources import load_entry_point
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3251, in
@_call_aside
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3235, in _call_aside
f(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3264, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 583, in _build_master
ws.require(requires)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 786, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rosdistro>=0.7.5' distribution was not found and is required by rosdep

**Comment by spanthr** [comment]
Solved it by:

sudo apt-get remove python2.7
sudo rm /usr/bin/python
sudo ln -s /usr/bin/python3 /usr/bin/python
sudo rosdep init
rosdep update
for "performance_test: Cannot locate rosdep definition for [test_osrf_testing_tools_cpp]"
sudo apt install ros-foxy-osrf-testing-tools-cpp

This does not help

**Comment by spanthr** [comment]
shaurya:~/ros2_ws/src$ rosdep install -y --from performance_test --ignore-src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
performance_test: Cannot locate rosdep definition for [test_osrf_testing_tools_cpp]

Please find a solution for this.

**Comment by spanthr** [comment]
Solve the above error by:

rosdep install -y --from performance_test --ignore-src -r -y --rosdistro foxy

This can be added to your read-me for any distro if it suits you.
Thanks.
