### ISSUE TITLE
:farmer: `test_performance_CycloneDDS_sync_PointCloud8m` timeout

### ISSUE THREAD

**Issue by Crola1702** [ros2/performance_test#59]
# Description

Reference build: https://build.ros2.org/job/Jci__nightly-performance_ubuntu_noble_amd64/57/

Test regressions:
* [projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m](https://build.ros2.org/job/Jci__nightly-performance_ubuntu_noble_amd64/57/testReport/junit/projectroot/test/test_performance_CycloneDDS_sync_PointCloud8m/)
* [buildfarm_perf_tests.PerformanceTestResults.test_results_CycloneDDS](https://build.ros2.org/job/Jci__nightly-performance_ubuntu_noble_amd64/57/testReport/junit/buildfarm_perf_tests/PerformanceTestResults/test_results_CycloneDDS_4/)

Log output:
```
FAIL: test_results_CycloneDDS (buildfarm_perf_tests.PerformanceTestResults.test_results_CycloneDDS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ws2/build_isolated/buildfarm_perf_tests/test/test/test_performance_CycloneDDS_sync_PointCloud8m.py", line 243, in test_results_CycloneDDS
    assert_wait_for_successful_exit(proc_info, process, timeout)
  File "/tmp/ws2/install_isolated/buildfarm_perf_tests/lib/python3.12/site-packages/buildfarm_perf_tests/launch.py", line 27, in assert_wait_for_successful_exit
    proc_info.assertWaitForShutdown(process, timeout=timeout)
  File "/tmp/ws/install_isolated/launch_testing/lib/python3.12/site-packages/launch_testing/proc_info_handler.py", line 141, in assertWaitForShutdown
    assert success, "Timed out waiting for process '{}' to finish".format(process)
           ^^^^^^^
AssertionError: Timed out waiting for process '<launch_ros.actions.node.Node object at 0x7fd6a0325a60>' to finish
```

<details>
<summary>
Times happened in Jazzy:
</summary>

error_name|package_name|job_name|build_number|build_datetime|node_name
-- | -- | -- | -- | -- | --
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|12|2024-05-30 01:15:37.701000|ci_agent-971db4f5
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|14|2024-06-06 00:59:48.110000|ci_agent-971db4f5
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|17|2024-07-03 00:01:17.073000|ci_agent-67b941c2
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|22|2024-07-27 03:01:30.931000|ci_agent-05cc7fc8
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|40|2024-09-30 00:01:42.323000|ci_agent-2e1ca0aa
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|44|2024-10-12 00:05:10.235000|ci_agent-238e8755
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|50|2024-11-02 00:47:48.555000|ci_agent-d223019c
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|52|2024-11-06 01:33:44.190000|ci_agent-d223019c
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|54|2024-11-21 02:06:44.310000|ci_agent-b87e62fb
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|55|2024-11-24 01:58:53.933000|ci_agent-d223019c
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|56|2024-11-30 01:40:45.296000|ci_agent-b87e62fb
projectroot.test.test_performance_CycloneDDS_sync_PointCloud8m|projectroot|Jci__nightly-performance_ubuntu_noble_amd64|57|2024-12-03 00:46:38.449000|ci_agent-b87e62fb

</details>

It is consistent since build 52. No code changes have been seen since build 23

**Comment by claraberendsen** [comment]
This seems to have been resolved, it has not appeared since March 23th.
